"""LISA Rich Rolling Fixture & Commercial Tier Data Generator.

Generates a realistic rolling catalog of 12 imminent matches (Today and Tomorrow)
across premier European leagues (EPL, La Liga, Bundesliga, Serie A, Ligue 1) and NBA.

Includes:
- Predictability ranking (from highest conviction down)
- Smart Market Pivots on marquee matches (e.g. pivoting away from coin-flip Moneylines
  to high-certainty Double Chance, Over 1.5, or BTTS)
- Tier 3 Syndicate Alpha data: Double-Poisson micro-bet matrices, Early Steam Radar,
  and Smart Correlated Parlay Builders.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone, timedelta
from typing import Any


def generate_rolling_commercial_dataset(now: datetime | None = None) -> dict[str, Any]:
    if now is None:
        now = datetime.now(timezone.utc)

    # 12 matches sorted by predictability/conviction descending
    picks = [
        {
            "rank": 1,
            "dedupe_key": "nba-thunder-wizards::h2h::Oklahoma City Thunder",
            "match_id": "nba-thunder-wizards",
            "sport_key": "basketball_nba",
            "league_label": "NBA",
            "home_team": "Oklahoma City Thunder",
            "away_team": "Washington Wizards",
            "kickoff_offset_hours": 1.75,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Oklahoma City Thunder",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.887,
            "fair_odds": 1.127,
            "best_book": "pinnacle",
            "best_odds": 1.16,
            "best_ev": 0.029,
            "conviction_score": 27.32,
            "recommended_stake_pct": 2.6,
            "recommended_units": 2.6,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+2.9% EV)",
            "tier_level": "FREE",  # Unlocked for all
            "books_odds": {"pinnacle": 1.16, "bet365": 1.15, "draftkings": 1.14},
        },
        {
            "rank": 2,
            "dedupe_key": "epl-arsenal-chelsea::totals::Over 1.5 Goals",
            "match_id": "epl-arsenal-chelsea",
            "sport_key": "soccer_epl",
            "league_label": "Premier League",
            "home_team": "Arsenal",
            "away_team": "Chelsea",
            "kickoff_offset_hours": 2.5,
            "market": "totals",
            "market_label": "Totals: Over 1.5 Goals",
            "outcome_name": "Over 1.5 Goals",
            "line": 1.5,
            "is_marquee": True,
            "pivot": {
                "original_market": "h2h",
                "hazard_reason": "Moneyline split (Arsenal 47% vs Chelsea 26% vs Draw 27% — coin-flip hazard).",
                "pivot_rationale": "LISA pivoted to Over 1.5 Goals for 88.9% structural Poisson certainty.",
                "moneyline_summary": "Arsenal (47%) / Draw (27%) / Chelsea (26%)"
            },
            "p_true": 0.889,
            "fair_odds": 1.125,
            "best_book": "bet365",
            "best_odds": 1.18,
            "best_ev": 0.049,
            "conviction_score": 26.85,
            "recommended_stake_pct": 2.5,
            "recommended_units": 2.5,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+4.9% EV)",
            "tier_level": "TELEGRAM_UNLOCK",  # Free tier unlocks via Telegram
            "books_odds": {"bet365": 1.18, "pinnacle": 1.16, "draftkings": 1.17},
        },
        {
            "rank": 3,
            "dedupe_key": "nba-celtics-hornets::h2h::Boston Celtics",
            "match_id": "nba-celtics-hornets",
            "sport_key": "basketball_nba",
            "league_label": "NBA",
            "home_team": "Boston Celtics",
            "away_team": "Charlotte Hornets",
            "kickoff_offset_hours": 3.75,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Boston Celtics",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.864,
            "fair_odds": 1.157,
            "best_book": "draftkings",
            "best_odds": 1.20,
            "best_ev": 0.037,
            "conviction_score": 24.50,
            "recommended_stake_pct": 2.2,
            "recommended_units": 2.2,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+3.7% EV)",
            "tier_level": "TELEGRAM_UNLOCK",  # Free tier unlocks via Telegram
            "books_odds": {"draftkings": 1.20, "bet365": 1.19, "pinnacle": 1.18},
        },
        {
            "rank": 4,
            "dedupe_key": "bdl-bayern-bochum::h2h::Bayern Munchen",
            "match_id": "bdl-bayern-bochum",
            "sport_key": "soccer_germany_bundesliga",
            "league_label": "Bundesliga",
            "home_team": "Bayern Munchen",
            "away_team": "Bochum",
            "kickoff_offset_hours": 4.5,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Bayern Munchen",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.848,
            "fair_odds": 1.179,
            "best_book": "bet365",
            "best_odds": 1.23,
            "best_ev": 0.043,
            "conviction_score": 23.80,
            "recommended_stake_pct": 2.3,
            "recommended_units": 2.3,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+4.3% EV)",
            "tier_level": "TIER_1",  # Unlocked in Tier 1 & above
            "books_odds": {"bet365": 1.23, "pinnacle": 1.21, "draftkings": 1.20},
        },
        {
            "rank": 5,
            "dedupe_key": "epl-mancity-southampton::h2h::Manchester City",
            "match_id": "epl-mancity-southampton",
            "sport_key": "soccer_epl",
            "league_label": "Premier League",
            "home_team": "Manchester City",
            "away_team": "Southampton",
            "kickoff_offset_hours": 5.25,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Manchester City",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.852,
            "fair_odds": 1.174,
            "best_book": "pinnacle",
            "best_odds": 1.21,
            "best_ev": 0.031,
            "conviction_score": 23.10,
            "recommended_stake_pct": 2.1,
            "recommended_units": 2.1,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+3.1% EV)",
            "tier_level": "TIER_1",  # Unlocked in Tier 1 & above
            "books_odds": {"pinnacle": 1.21, "bet365": 1.20, "draftkings": 1.19},
        },
        {
            "rank": 6,
            "dedupe_key": "lig-madrid-atletico::double_chance::Real Madrid or Draw",
            "match_id": "lig-madrid-atletico",
            "sport_key": "soccer_spain_la_liga",
            "league_label": "La Liga",
            "home_team": "Real Madrid",
            "away_team": "Atletico Madrid",
            "kickoff_offset_hours": 6.5,
            "market": "double_chance",
            "market_label": "Double Chance: 1X (Real Madrid or Draw)",
            "outcome_name": "Real Madrid or Draw",
            "line": None,
            "is_marquee": True,
            "pivot": {
                "original_market": "h2h",
                "hazard_reason": "High-profile Madrid Derby: Moneyline is razor-thin (Madrid 48% vs Atletico 24% vs Draw 28%).",
                "pivot_rationale": "LISA pivoted to Double Chance (1X) capturing 82.8% true safety margin.",
                "moneyline_summary": "Real Madrid (48%) / Draw (28%) / Atletico (24%)"
            },
            "p_true": 0.828,
            "fair_odds": 1.208,
            "best_book": "bet365",
            "best_odds": 1.26,
            "best_ev": 0.043,
            "conviction_score": 20.40,
            "recommended_stake_pct": 2.0,
            "recommended_units": 2.0,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+4.3% EV)",
            "tier_level": "TIER_2",  # Unlocked in Tier 2 & above
            "books_odds": {"bet365": 1.26, "pinnacle": 1.24, "draftkings": 1.23},
        },
        {
            "rank": 7,
            "dedupe_key": "nba-nuggets-pistons::h2h::Denver Nuggets",
            "match_id": "nba-nuggets-pistons",
            "sport_key": "basketball_nba",
            "league_label": "NBA",
            "home_team": "Denver Nuggets",
            "away_team": "Detroit Pistons",
            "kickoff_offset_hours": 8.0,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Denver Nuggets",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.841,
            "fair_odds": 1.189,
            "best_book": "draftkings",
            "best_odds": 1.22,
            "best_ev": 0.026,
            "conviction_score": 19.80,
            "recommended_stake_pct": 1.8,
            "recommended_units": 1.8,
            "freshness": "FAIR",
            "badge_color": "amber",
            "gauge_text": "Fair Value (+2.6% EV)",
            "tier_level": "TIER_2",
            "books_odds": {"draftkings": 1.22, "bet365": 1.21, "pinnacle": 1.20},
        },
        {
            "rank": 8,
            "dedupe_key": "ita-inter-juventus::double_chance::Inter Milan or Draw",
            "match_id": "ita-inter-juventus",
            "sport_key": "soccer_italy_serie_a",
            "league_label": "Serie A",
            "home_team": "Inter Milan",
            "away_team": "Juventus",
            "kickoff_offset_hours": 18.5,
            "market": "double_chance",
            "market_label": "Double Chance: 1X (Inter or Draw)",
            "outcome_name": "Inter Milan or Draw",
            "line": None,
            "is_marquee": True,
            "pivot": {
                "original_market": "h2h",
                "hazard_reason": "Derby d'Italia: Moneyline split (Inter 45% vs Draw 31% vs Juventus 24%).",
                "pivot_rationale": "LISA pivoted to Double Chance (1X) yielding 81.6% true probability against tactical stalemate.",
                "moneyline_summary": "Inter Milan (45%) / Draw (31%) / Juventus (24%)"
            },
            "p_true": 0.816,
            "fair_odds": 1.225,
            "best_book": "pinnacle",
            "best_odds": 1.28,
            "best_ev": 0.044,
            "conviction_score": 18.20,
            "recommended_stake_pct": 1.9,
            "recommended_units": 1.9,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+4.4% EV)",
            "tier_level": "TIER_2",
            "books_odds": {"pinnacle": 1.28, "bet365": 1.27, "draftkings": 1.25},
        },
        {
            "rank": 9,
            "dedupe_key": "nba-lakers-warriors::totals::Over 221.5 Points",
            "match_id": "nba-lakers-warriors",
            "sport_key": "basketball_nba",
            "league_label": "NBA",
            "home_team": "Los Angeles Lakers",
            "away_team": "Golden State Warriors",
            "kickoff_offset_hours": 20.0,
            "market": "totals",
            "market_label": "Totals: Over 221.5 Points",
            "outcome_name": "Over 221.5 Points",
            "line": 221.5,
            "is_marquee": True,
            "pivot": {
                "original_market": "spreads",
                "hazard_reason": "High-variance point spread (-1.5 vs +1.5) susceptible to late-foul garbage time.",
                "pivot_rationale": "LISA pivoted to Game Totals Over 221.5 for 79.8% structural pace consensus.",
                "moneyline_summary": "Lakers (-1.5) vs Warriors (+1.5)"
            },
            "p_true": 0.798,
            "fair_odds": 1.253,
            "best_book": "bet365",
            "best_odds": 1.31,
            "best_ev": 0.045,
            "conviction_score": 16.90,
            "recommended_stake_pct": 1.7,
            "recommended_units": 1.7,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+4.5% EV)",
            "tier_level": "TIER_2",
            "books_odds": {"bet365": 1.31, "draftkings": 1.30, "pinnacle": 1.29},
        },
        {
            "rank": 10,
            "dedupe_key": "fra-psg-angers::h2h::Paris Saint-Germain",
            "match_id": "fra-psg-angers",
            "sport_key": "soccer_france_ligue_one",
            "league_label": "Ligue 1",
            "home_team": "Paris Saint-Germain",
            "away_team": "Angers",
            "kickoff_offset_hours": 21.5,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Paris Saint-Germain",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.835,
            "fair_odds": 1.198,
            "best_book": "bet365",
            "best_odds": 1.24,
            "best_ev": 0.035,
            "conviction_score": 19.10,
            "recommended_stake_pct": 1.9,
            "recommended_units": 1.9,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+3.5% EV)",
            "tier_level": "TIER_2",
            "books_odds": {"bet365": 1.24, "pinnacle": 1.22, "draftkings": 1.21},
        },
        {
            "rank": 11,
            "dedupe_key": "epl-liverpool-newcastle::totals::BTTS Yes",
            "match_id": "epl-liverpool-newcastle",
            "sport_key": "soccer_epl",
            "league_label": "Premier League",
            "home_team": "Liverpool",
            "away_team": "Newcastle",
            "kickoff_offset_hours": 23.0,
            "market": "derived_btts",
            "market_label": "Derived: Both Teams To Score (BTTS Yes)",
            "outcome_name": "BTTS Yes",
            "line": None,
            "is_marquee": True,
            "pivot": {
                "original_market": "h2h",
                "hazard_reason": "Liverpool ML is priced with heavy retail tax @ 1.45 (true prob 54%).",
                "pivot_rationale": "LISA Double-Poisson kernel derived BTTS Yes @ 80.4% true probability.",
                "moneyline_summary": "Liverpool (54%) / Draw (23%) / Newcastle (23%)"
            },
            "p_true": 0.804,
            "fair_odds": 1.244,
            "best_book": "pinnacle",
            "best_odds": 1.30,
            "best_ev": 0.045,
            "conviction_score": 17.10,
            "recommended_stake_pct": 1.7,
            "recommended_units": 1.7,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+4.5% EV)",
            "tier_level": "TIER_2",
            "books_odds": {"pinnacle": 1.30, "bet365": 1.29, "draftkings": 1.28},
        },
        {
            "rank": 12,
            "dedupe_key": "lig-barcelona-laspalmas::h2h::Barcelona",
            "match_id": "lig-barcelona-laspalmas",
            "sport_key": "soccer_spain_la_liga",
            "league_label": "La Liga",
            "home_team": "Barcelona",
            "away_team": "Las Palmas",
            "kickoff_offset_hours": 24.5,
            "market": "h2h",
            "market_label": "Moneyline (H2H)",
            "outcome_name": "Barcelona",
            "line": None,
            "is_marquee": False,
            "pivot": None,
            "p_true": 0.831,
            "fair_odds": 1.203,
            "best_book": "bet365",
            "best_odds": 1.25,
            "best_ev": 0.039,
            "conviction_score": 19.30,
            "recommended_stake_pct": 1.9,
            "recommended_units": 1.9,
            "freshness": "FRESH",
            "badge_color": "emerald",
            "gauge_text": "Optimal Entry (+3.9% EV)",
            "tier_level": "TIER_2",
            "books_odds": {"bet365": 1.25, "pinnacle": 1.23, "draftkings": 1.22},
        },
    ]

    # Calculate actual commence_time ISO strings and human kickoff strings
    for p in picks:
        commence = now + timedelta(hours=p["kickoff_offset_hours"])
        p["commence_time"] = commence.isoformat()
        hrs = int(p["kickoff_offset_hours"])
        mins = int((p["kickoff_offset_hours"] - hrs) * 60)
        if hrs < 24:
            p["kickoff_human"] = f"Today in {hrs}h {mins:02d}m" if hrs > 0 else f"Today in {mins}m"
        else:
            p["kickoff_human"] = f"Tomorrow in {hrs-24}h {mins:02d}m"

        p["deep_links"] = {
            "pinnacle": f"https://www.pinnacle.com/en/search/{p['home_team'].replace(' ', '%20')}",
            "bet365": f"https://www.bet365.com/#/AX/K^{p['home_team'].replace(' ', '%20')}/",
            "draftkings": f"https://sportsbook.draftkings.com/search?q={p['home_team'].replace(' ', '%20')}",
        }

    # Tier 3 Syndicate Alpha Data
    tier3_alpha = {
        "poisson_micro_bets": [
            {
                "match": "Arsenal vs Chelsea",
                "league": "Premier League",
                "kickoff": "Today in 2h 30m",
                "derived_market": "Both Teams To Score (BTTS Yes)",
                "p_true": 0.742,
                "fair_odds": 1.348,
                "market_odds": 1.44,
                "alpha_ev": "+6.8%",
                "syndicate_rating": "AAA",
            },
            {
                "match": "Arsenal vs Chelsea",
                "league": "Premier League",
                "kickoff": "Today in 2h 30m",
                "derived_market": "Over 2.5 Match Goals",
                "p_true": 0.684,
                "fair_odds": 1.462,
                "market_odds": 1.58,
                "alpha_ev": "+8.1%",
                "syndicate_rating": "AAA+",
            },
            {
                "match": "Real Madrid vs Atletico Madrid",
                "league": "La Liga",
                "kickoff": "Today in 6h 30m",
                "derived_market": "Team Total: Real Madrid Over 1.5 Goals",
                "p_true": 0.718,
                "fair_odds": 1.393,
                "market_odds": 1.50,
                "alpha_ev": "+7.7%",
                "syndicate_rating": "AAA",
            },
            {
                "match": "Inter Milan vs Juventus",
                "league": "Serie A",
                "kickoff": "Tomorrow in 18h 30m",
                "derived_market": "Under 2.5 Match Goals",
                "p_true": 0.765,
                "fair_odds": 1.307,
                "market_odds": 1.40,
                "alpha_ev": "+7.1%",
                "syndicate_rating": "AAA",
            },
            {
                "match": "Liverpool vs Newcastle",
                "league": "Premier League",
                "kickoff": "Tomorrow in 23h 00m",
                "derived_market": "Team Total: Liverpool Over 1.5 Goals",
                "p_true": 0.778,
                "fair_odds": 1.285,
                "market_odds": 1.38,
                "alpha_ev": "+7.4%",
                "syndicate_rating": "AAA+",
            },
        ],
        "early_steam_radar": [
            {
                "signal_id": "stm-01",
                "match": "Arsenal vs Chelsea",
                "market": "Over 1.5 Goals",
                "sharp_book": "Pinnacle",
                "sharp_line": 1.15,
                "sharp_shift": "-5.7% (Sharp Steam Inflow)",
                "lagging_book": "Bet365",
                "lagging_line": 1.20,
                "clv_window_remaining": "04m 12s",
                "arb_ev": "+4.3% Guaranteed CLV",
                "status": "ACTIVE_STEAM",
            },
            {
                "signal_id": "stm-02",
                "match": "Real Madrid vs Atletico Madrid",
                "market": "Real Madrid 1X",
                "sharp_book": "Circa / Pinnacle",
                "sharp_line": 1.22,
                "sharp_shift": "-4.2% (Steam Inflow)",
                "lagging_book": "DraftKings",
                "lagging_line": 1.28,
                "clv_window_remaining": "06m 45s",
                "arb_ev": "+4.9% Guaranteed CLV",
                "status": "ACTIVE_STEAM",
            },
            {
                "signal_id": "stm-03",
                "match": "Boston Celtics vs Charlotte Hornets",
                "market": "Celtics ML",
                "sharp_book": "Pinnacle",
                "sharp_line": 1.17,
                "sharp_shift": "-2.5% (Limit Max Bet)",
                "lagging_book": "Bet365",
                "lagging_line": 1.21,
                "clv_window_remaining": "02m 30s",
                "arb_ev": "+3.4% Guaranteed CLV",
                "status": "ACTIVE_STEAM",
            },
        ],
        "smart_parlays": [
            {
                "title": "💎 Diamond 2-Leg Exponential Compounder",
                "legs": [
                    "Bayern Munchen (H2H) @ 1.23 (P_true: 84.8%)",
                    "Real Madrid vs Atletico Over 1.5 Goals @ 1.18 (P_true: 88.9%)"
                ],
                "combined_fair_odds": 1.326,
                "combined_market_odds": 1.451,
                "joint_probability": 0.754,
                "compounding_ev": "+9.4% EV",
                "recommended_portfolio_kelly": "3.8 units",
                "hedge_strategy": "Zero hedge required; joint certainty exceeds 75% floor.",
            },
            {
                "title": "👑 Institutional 3-Leg Syndicate Treble",
                "legs": [
                    "Thunder (H2H) @ 1.16 (P_true: 88.7%)",
                    "Arsenal vs Chelsea Over 1.5 Goals @ 1.18 (P_true: 88.9%)",
                    "Boston Celtics (H2H) @ 1.20 (P_true: 86.4%)"
                ],
                "combined_fair_odds": 1.470,
                "combined_market_odds": 1.643,
                "joint_probability": 0.681,
                "compounding_ev": "+11.8% EV",
                "recommended_portfolio_kelly": "3.1 units",
                "hedge_strategy": "Optional late hedge on Leg 3 if Legs 1 & 2 clear.",
            }
        ],
        "vip_telegram_feed": {
            "channel": "@LISA_VIP_Institutional_Alpha",
            "subscribers": "142 Institutional Seats",
            "latency": "< 450ms direct WebSocket stream",
            "inline_buttons_enabled": True,
        }
    }

    # Settled ledger sample
    settled_ledger = [
        {
            "dedupe_key": "epl-arsenal-wolves::h2h::Arsenal",
            "match_id": "epl-arsenal-wolves",
            "sport_key": "soccer_epl",
            "market": "h2h",
            "outcome_name": "Arsenal",
            "home_team": "Arsenal",
            "away_team": "Wolves",
            "commence_time": (now - timedelta(days=1)).isoformat(),
            "p_true": 0.845,
            "fair_odds": 1.183,
            "n_books": 5,
            "stdev": 0.011,
            "cv": 0.013,
            "state": "SETTLED",
            "result": "WIN",
            "best_book": "bet365",
            "best_odds": 1.24,
            "best_ev": 0.048,
            "closing_odds": 1.20,
            "closing_p_true": 0.850,
            "clv": 0.033,  # +3.3% CLV
            "conviction_score": 24.1,
            "recommended_stake_pct": 2.2,
            "recommended_units": 2.2,
            "settled_at": (now - timedelta(hours=18)).isoformat(),
        },
        {
            "dedupe_key": "nba-bucks-wizards::h2h::Milwaukee Bucks",
            "match_id": "nba-bucks-wizards",
            "sport_key": "basketball_nba",
            "market": "h2h",
            "outcome_name": "Milwaukee Bucks",
            "home_team": "Milwaukee Bucks",
            "away_team": "Washington Wizards",
            "commence_time": (now - timedelta(days=2)).isoformat(),
            "p_true": 0.862,
            "fair_odds": 1.160,
            "n_books": 5,
            "stdev": 0.009,
            "cv": 0.010,
            "state": "SETTLED",
            "result": "WIN",
            "best_book": "pinnacle",
            "best_odds": 1.20,
            "best_ev": 0.034,
            "closing_odds": 1.18,
            "closing_p_true": 0.865,
            "clv": 0.017,  # +1.7% CLV
            "conviction_score": 25.4,
            "recommended_stake_pct": 2.3,
            "recommended_units": 2.3,
            "settled_at": (now - timedelta(days=1, hours=20)).isoformat(),
        },
        {
            "dedupe_key": "lig-madrid-valladolid::h2h::Real Madrid",
            "match_id": "lig-madrid-valladolid",
            "sport_key": "soccer_spain_la_liga",
            "market": "h2h",
            "outcome_name": "Real Madrid",
            "home_team": "Real Madrid",
            "away_team": "Valladolid",
            "commence_time": (now - timedelta(days=3)).isoformat(),
            "p_true": 0.855,
            "fair_odds": 1.170,
            "n_books": 5,
            "stdev": 0.012,
            "cv": 0.014,
            "state": "SETTLED",
            "result": "WIN",
            "best_book": "bet365",
            "best_odds": 1.22,
            "best_ev": 0.043,
            "closing_odds": 1.19,
            "closing_p_true": 0.860,
            "clv": 0.025,  # +2.5% CLV
            "conviction_score": 23.5,
            "recommended_stake_pct": 2.1,
            "recommended_units": 2.1,
            "settled_at": (now - timedelta(days=2, hours=22)).isoformat(),
        },
        {
            "dedupe_key": "bdl-leverkusen-heidenheim::totals::Over 1.5 Goals",
            "match_id": "bdl-leverkusen-heidenheim",
            "sport_key": "soccer_germany_bundesliga",
            "market": "totals",
            "outcome_name": "Over 1.5 Goals",
            "home_team": "Bayer Leverkusen",
            "away_team": "Heidenheim",
            "commence_time": (now - timedelta(days=4)).isoformat(),
            "p_true": 0.890,
            "fair_odds": 1.124,
            "n_books": 5,
            "stdev": 0.007,
            "cv": 0.008,
            "state": "SETTLED",
            "result": "WIN",
            "best_book": "bet365",
            "best_odds": 1.18,
            "best_ev": 0.050,
            "closing_odds": 1.14,
            "closing_p_true": 0.895,
            "clv": 0.035,  # +3.5% CLV
            "conviction_score": 28.1,
            "recommended_stake_pct": 2.8,
            "recommended_units": 2.8,
            "settled_at": (now - timedelta(days=3, hours=21)).isoformat(),
        },
        {
            "dedupe_key": "ita-napoli-monza::h2h::Napoli",
            "match_id": "ita-napoli-monza",
            "sport_key": "soccer_italy_serie_a",
            "market": "h2h",
            "outcome_name": "Napoli",
            "home_team": "Napoli",
            "away_team": "Monza",
            "commence_time": (now - timedelta(days=5)).isoformat(),
            "p_true": 0.825,
            "fair_odds": 1.212,
            "n_books": 5,
            "stdev": 0.014,
            "cv": 0.017,
            "state": "SETTLED",
            "result": "WIN",
            "best_book": "pinnacle",
            "best_odds": 1.25,
            "best_ev": 0.031,
            "closing_odds": 1.23,
            "closing_p_true": 0.830,
            "clv": 0.016,  # +1.6% CLV
            "conviction_score": 20.2,
            "recommended_stake_pct": 1.9,
            "recommended_units": 1.9,
            "settled_at": (now - timedelta(days=4, hours=20)).isoformat(),
        },
    ]

    return {
        "meta": {
            "generated_at": now.isoformat(),
            "version": "0.1.0",
            "total_sports": 9,
            "scope_leagues": [
                "soccer_epl",
                "soccer_spain_la_liga",
                "soccer_germany_bundesliga",
                "soccer_italy_serie_a",
                "soccer_france_ligue_one",
                "basketball_nba",
            ]
        },
        "summary": {
            "active_picks_count": len(picks),
            "settled_picks_count": len(settled_ledger),
            "win_rate": 1.0,
            "brier_score": 0.0248,
            "ece": 0.082,
            "mean_clv": 0.0252,  # +2.52% Mean CLV across all picks
            "positive_clv_share": 1.0,
        },
        "tier_config": {
            "free": {
                "label": "Free Tier",
                "unlocked_count": 1,
                "telegram_unlock_count": 2,
                "locked_count": 9,
                "cta": "Upgrade to Tier 2 to unlock all 12 daily consensus picks",
            },
            "tier1": {
                "label": "Tier 1 Starter ($19/mo)",
                "unlocked_count": 5,
                "locked_count": 7,
                "cta": "Upgrade to Tier 2 for full 12-match access & Kelly Calculator",
            },
            "tier2": {
                "label": "Tier 2 Pro ($49/mo)",
                "unlocked_count": 12,
                "locked_count": 0,
                "features": [
                    "All 12 Daily Consensus Picks Unlocked",
                    "1-Click Bet Slip Execution",
                    "Dynamic Slippage Guard",
                    "Interactive Kelly Bankroll Advisor"
                ]
            },
            "tier3": {
                "label": "Tier 3 VIP Alpha ($249/mo)",
                "features": [
                    "All 12 Daily Consensus Picks Unlocked",
                    "Poisson Micro-Bet Derivative Matrix (BTTS, Over 1.5, Double Chance)",
                    "Sub-Second Early Steam & CLV Arbitrage Radar",
                    "Smart Correlated Parlay Builder (Compounding Kelly Math)",
                    "Direct VIP Telegram Bot with Native Inline Execution Slips"
                ]
            }
        },
        "active_picks": picks,
        "settled_ledger": settled_ledger,
        "calibration": {
            "sample_size": len(settled_ledger),
            "brier_score": 0.0248,
            "murphy": {
                "reliability": 0.0034,
                "resolution": 0.0982,
                "uncertainty": 0.1196
            },
            "ece": 0.082,
            "mce": 0.115,
            "log_loss": 0.162,
            "bins": [
                {"bin_lower": 0.70, "bin_upper": 0.80, "count": 1, "mean_p_true": 0.78, "empirical_accuracy": 1.0},
                {"bin_lower": 0.80, "bin_upper": 0.90, "count": 4, "mean_p_true": 0.85, "empirical_accuracy": 1.0}
            ]
        },
        "tier3_alpha": tier3_alpha,
    }
