"""Longshot Ticket — 30-day accumulated parlay for Tier 3.

The longshot ticket is a signature Tier 3 feature:
- 2 best picks per day, every day for 30 days
- All 60 picks accumulated into one parlay ticket
- Massive odds (potentially 1000x+)
- Auto-generated by the system, user can also curate

The ticket tracks:
- Daily picks (2 per day)
- Cumulative odds
- Status (open, won, lost, void)
- Payout calculation
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from .odds import utcnow
from .storage import Storage

logger = logging.getLogger(__name__)

#: Number of days the longshot ticket runs
TICKET_DURATION_DAYS = 30

#: Number of picks per day
PICKS_PER_DAY = 2


@dataclass
class LongshotPick:
    """A single pick in the longshot ticket."""
    date: str  # ISO date string
    match_id: str
    sport_key: str
    home_team: str
    away_team: str
    outcome_name: str
    market: str
    odds: float
    conviction_score: float
    result: Optional[str] = None  # WIN, LOSS, VOID, None (pending)

    def to_dict(self) -> dict[str, Any]:
        return {
            "date": self.date,
            "match_id": self.match_id,
            "sport_key": self.sport_key,
            "home_team": self.home_team,
            "away_team": self.away_team,
            "outcome_name": self.outcome_name,
            "market": self.market,
            "odds": self.odds,
            "conviction_score": self.conviction_score,
            "result": self.result,
        }


@dataclass
class LongshotTicket:
    """A 30-day accumulated parlay ticket."""
    ticket_id: str
    user_id: str
    start_date: str  # ISO date
    end_date: str  # ISO date
    picks: list[LongshotPick] = field(default_factory=list)
    status: str = "open"  # open, won, lost, void
    total_odds: float = 1.0
    potential_payout: float = 0.0
    stake: float = 1.0
    created_at: datetime = field(default_factory=lambda: utcnow())
    settled_at: Optional[datetime] = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "ticket_id": self.ticket_id,
            "user_id": self.user_id,
            "start_date": self.start_date,
            "end_date": self.end_date,
            "picks": [p.to_dict() for p in self.picks],
            "status": self.status,
            "total_odds": round(self.total_odds, 2),
            "potential_payout": round(self.potential_payout, 2),
            "stake": self.stake,
            "created_at": self.created_at.isoformat(),
            "settled_at": self.settled_at.isoformat() if self.settled_at else None,
        }


class LongshotTicketManager:
    """Manages 30-day longshot parlay tickets for Tier 3 users.

    The manager:
    1. Creates tickets with 2 best picks per day for 30 days
    2. Tracks cumulative odds
    3. Updates pick results as matches settle
    4. Settles the ticket when all picks are decided
    """

    def __init__(self, *, storage: Storage):
        self.storage = storage

    def create_ticket(self, user_id: str, picks: list[dict], *,
                      stake: float = 1.0,
                      now: Optional[datetime] = None) -> LongshotTicket:
        """Create a new longshot ticket.

        Args:
            user_id: User ID
            picks: List of picks (should be 60 picks = 2 per day for 30 days)
            stake: Stake amount
            now: Reference time

        Returns:
            LongshotTicket
        """
        now = now or utcnow()
        start_date = now.date().isoformat()
        end_date = (now + timedelta(days=TICKET_DURATION_DAYS)).date().isoformat()

        # Create longshot picks
        longshot_picks = []
        total_odds = 1.0

        for pick_data in picks:
            pick = LongshotPick(
                date=pick_data.get("date", start_date),
                match_id=pick_data["match_id"],
                sport_key=pick_data.get("sport_key", ""),
                home_team=pick_data.get("home_team", ""),
                away_team=pick_data.get("away_team", ""),
                outcome_name=pick_data["outcome_name"],
                market=pick_data.get("market", "h2h"),
                odds=pick_data.get("odds", 1.0),
                conviction_score=pick_data.get("conviction_score", 0.0),
            )
            longshot_picks.append(pick)
            total_odds *= pick.odds

        ticket = LongshotTicket(
            ticket_id=f"longshot_{user_id}_{start_date}",
            user_id=user_id,
            start_date=start_date,
            end_date=end_date,
            picks=longshot_picks,
            total_odds=total_odds,
            potential_payout=stake * total_odds,
            stake=stake,
            created_at=now,
        )

        logger.info(
            "Created longshot ticket %s: %d picks, total odds %.2f, potential payout %.2f",
            ticket.ticket_id, len(longshot_picks), total_odds, ticket.potential_payout,
        )

        return ticket

    def update_pick_result(self, ticket: LongshotTicket, match_id: str,
                           result: str) -> None:
        """Update a pick result in the ticket.

        Args:
            ticket: The longshot ticket
            match_id: Match ID to update
            result: Result (WIN, LOSS, VOID)
        """
        for pick in ticket.picks:
            if pick.match_id == match_id:
                pick.result = result
                break

        # Check if all picks are decided
        if all(p.result is not None for p in ticket.picks):
            self._settle_ticket(ticket)

    def _settle_ticket(self, ticket: LongshotTicket) -> None:
        """Settle the ticket based on all pick results."""
        # If any pick is VOID, remove it from the odds calculation
        # If any pick is LOSS, the ticket is lost
        # If all picks are WIN, the ticket is won

        has_loss = any(p.result == "LOSS" for p in ticket.picks)
        all_won = all(p.result == "WIN" for p in ticket.picks)

        if has_loss:
            ticket.status = "lost"
        elif all_won:
            ticket.status = "won"
        else:
            ticket.status = "void"

        ticket.settled_at = utcnow()

        logger.info(
            "Settled longshot ticket %s: %s (odds: %.2f, payout: %.2f)",
            ticket.ticket_id, ticket.status, ticket.total_odds, ticket.potential_payout,
        )

    def get_ticket_status(self, ticket: LongshotTicket) -> dict[str, Any]:
        """Get the current status of a ticket."""
        pending = sum(1 for p in ticket.picks if p.result is None)
        won = sum(1 for p in ticket.picks if p.result == "WIN")
        lost = sum(1 for p in ticket.picks if p.result == "LOSS")
        void = sum(1 for p in ticket.picks if p.result == "VOID")

        return {
            "ticket_id": ticket.ticket_id,
            "status": ticket.status,
            "total_picks": len(ticket.picks),
            "pending": pending,
            "won": won,
            "lost": lost,
            "void": void,
            "total_odds": round(ticket.total_odds, 2),
            "potential_payout": round(ticket.potential_payout, 2),
            "progress": f"{won + lost + void}/{len(ticket.picks)}",
        }

    def generate_daily_picks(self, date: str, available_picks: list[dict]) -> list[dict]:
        """Generate the 2 best picks for a given day.

        Args:
            date: Date string (ISO format)
            available_picks: List of available picks for the day

        Returns:
            List of 2 picks (the best ones by conviction score)
        """
        # Sort by conviction score (highest first)
        sorted_picks = sorted(
            available_picks,
            key=lambda p: p.get("conviction_score", 0.0),
            reverse=True,
        )

        # Select top 2
        daily_picks = sorted_picks[:PICKS_PER_DAY]

        # Add date to each pick
        for pick in daily_picks:
            pick["date"] = date

        return daily_picks


# Global manager instance
longshot_manager = LongshotTicketManager(storage=None)  # Will be initialized with storage when needed
