"""PostgreSQL schema v1. Subsequent changes require a new migration."""
SCHEMA_V1 = """
CREATE TABLE IF NOT EXISTS picks (
    dedupe_key    TEXT PRIMARY KEY,
    match_id      TEXT NOT NULL,
    sport_key     TEXT NOT NULL,
    market        TEXT NOT NULL,
    outcome_name  TEXT NOT NULL,
    line          DOUBLE PRECISION,
    home_team     TEXT,
    away_team     TEXT,
    commence_time TEXT,
    p_true        DOUBLE PRECISION NOT NULL,
    fair_odds     DOUBLE PRECISION NOT NULL,
    n_books       INTEGER NOT NULL,
    stdev         DOUBLE PRECISION,
    cv            DOUBLE PRECISION,
    state         TEXT NOT NULL,
    result        TEXT,
    best_book     TEXT,
    best_odds     DOUBLE PRECISION,
    best_ev       DOUBLE PRECISION,
    closing_odds  DOUBLE PRECISION,
    closing_p_true DOUBLE PRECISION,
    clv           DOUBLE PRECISION,
    conviction_score DOUBLE PRECISION DEFAULT 0.0,
    recommended_stake_pct DOUBLE PRECISION DEFAULT 0.0,
    recommended_units DOUBLE PRECISION DEFAULT 0.0,
    created_at    TEXT NOT NULL,
    settled_at    TEXT,
    source        TEXT DEFAULT 'consensus',
    basis         TEXT,
    is_recommendation INTEGER DEFAULT 1,
    model_version TEXT,
    actual_score  TEXT,
    result_source TEXT
);
CREATE INDEX IF NOT EXISTS idx_picks_state ON picks(state);
CREATE INDEX IF NOT EXISTS idx_picks_match ON picks(match_id);
CREATE INDEX IF NOT EXISTS idx_picks_created ON picks(created_at);

CREATE TABLE IF NOT EXISTS live_cache (
    key           TEXT PRIMARY KEY,
    data          TEXT NOT NULL,
    expires_at    DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_live_expires ON live_cache(expires_at);

CREATE TABLE IF NOT EXISTS verified_sessions (
    web_user_id      TEXT PRIMARY KEY,
    telegram_user_id TEXT,
    username         TEXT,
    verified_at      DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS system_telemetry (
    key           TEXT PRIMARY KEY,
    val_json      TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id                TEXT PRIMARY KEY,
    email             TEXT UNIQUE NOT NULL,
    password_hash     TEXT NOT NULL,
    password_salt     TEXT NOT NULL,
    display_name      TEXT,
    tier              TEXT NOT NULL DEFAULT 'free',
    telegram_id       TEXT,
    telegram_username TEXT,
    telegram_verified INTEGER NOT NULL DEFAULT 0,
    created_at        DOUBLE PRECISION NOT NULL,
    updated_at        DOUBLE PRECISION NOT NULL,
    last_login_at     DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_telegram ON users(telegram_id);

CREATE TABLE IF NOT EXISTS sessions (
    session_id        TEXT PRIMARY KEY,
    user_id           TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at        DOUBLE PRECISION NOT NULL,
    expires_at        DOUBLE PRECISION NOT NULL,
    ip_address        TEXT,
    user_agent        TEXT
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id   TEXT NOT NULL,
    action     TEXT NOT NULL,
    target     TEXT,
    details    TEXT,
    timestamp  DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_admin ON admin_audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_time ON admin_audit_logs(timestamp);

-- Durable notification outbox: a pick is written to the ledger before its alert
-- is delivered, so an at-most-once dispatch silently drops alerts on failure.
-- Rows stay PENDING until a notifier confirms delivery, and are retried.
CREATE TABLE IF NOT EXISTS notification_outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key    TEXT NOT NULL UNIQUE,
    text          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'PENDING',
    attempts      INTEGER NOT NULL DEFAULT 0,
    last_error    TEXT,
    created_at    DOUBLE PRECISION NOT NULL,
    sent_at       DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_outbox_status ON notification_outbox(status, id);


CREATE TABLE IF NOT EXISTS worker_leases (
    name TEXT PRIMARY KEY, owner TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS daily_publications (
    day TEXT PRIMARY KEY, generated_at TEXT NOT NULL, payload TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_forecast_due ON picks(source, state, commence_time, sport_key);
CREATE TABLE IF NOT EXISTS user_bankroll_profiles (
    user_id TEXT PRIMARY KEY, username TEXT, bankroll_amount DOUBLE PRECISION NOT NULL,
    risk_profile TEXT NOT NULL, kelly_fraction DOUBLE PRECISION NOT NULL,
    preferred_bookmaker TEXT NOT NULL, updated_at DOUBLE PRECISION NOT NULL
);
CREATE OR REPLACE VIEW lisa_predictions AS SELECT * FROM picks;
CREATE OR REPLACE VIEW user_profiles AS SELECT * FROM users;
"""
